config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :tasks
  resources :projects
  resources :clients
  resources :types
  resources :task_statuses
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  def index
    @types = Type.all
  end

  # GET /types/new
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  def edit
  end

  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Project Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type}
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:name, :description, :type_id)
    end
end

app/helpers/type_helper.rb
module TypeHelper
end

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :type_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :type_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/types/edit.html.erb
<h1>Editing Project Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Types</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type.description %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Project Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', :back %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project Type:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Project Type Description:</strong>
  <%= @type.description %>
</p>

<%= link_to 'Back', types_path %> |
<%= link_to 'Edit', edit_type_path %> |
<%= link_to 'Delete', type_path(@type), method: :delete, data: { confirm: 'Are you sure?' } %>