config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :tasks
  resources :projects
  resources :clients
  resources :types
  resources :task_statuses
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'

end

app/views/layouts/_main_navbar.html.erb
<div class="row">
  <ul class="menu">
    <% if user_signed_in? %>
      <li>
        <%= link_to('Dashboard', root_path) %>
      </li>
      <li>
        <%= link_to('Clients', clients_path) %>
      </li>
      <li>
        <%= link_to('Tasks', tasks_path) %>
      </li>
      <li>
        <%= link_to('Projects', projects_path) %>
      </li>
      <li>
        <%= link_to('Project Types', types_path) %>
      </li>
      <li>
        <%= link_to('Task Statuses', task_statuses_path) %>
      </li>
    <% else %>
    <% end %>
  </ul>
</div>

app/views/layouts/_top_navbar.html.erb
<div class="top-navbar">
  <div class="row">
    <div class="large-1 columns"></div>
    <div class="large-11 columns">
      <ul class="menu align-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li>
            <%= link_to('Home', root_path) %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/top_navbar" %>
    <%= render "layouts/main_navbar" %>
    <%= yield %>

  </body>
</html>